### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ghost** [MrS0m30n3/youtube-dl-gui#114]
Hi
I wonder when the new gui are released. I want some functions like increase the working numbers. I read in the issues and i try to change json file but it dosent work for me.

I also want to delete finished files from download list.
It is possible to choose wich resolution on the download file i want to download?

**Comment by MrS0m30n3** [comment]
I dont really have a release schedule the new gui will be available when it is ready. Feel free to contribute in order to help the project. Currently you can change the number of parallel downloads by editing your config file. The deletion of finished files from the download list has also been requested by another user so its going to be added in the future. Now for the resolution, have you checked the Options > Video tab?
