### ISSUE TITLE
include dynamic format options

### ISSUE THREAD

**Issue by Jan02** [MrS0m30n3/youtube-dl-gui#116]
@MrS0m30n3 you need to include the new formats that are dynamic:
    **best**: Select best quality format represented by single file with video and audio
    **wors**t: Select worst quality format represented by single file with video and audio
    **bestvideo**: Select best quality video only format (e.g. DASH video), may not be available
    **worstvideo**: Select worst quality video only format, may not be available
    **bestaudio**: Select best quality audio only format, may not be available
    **worstaudio**: Select worst quality audio only format, may not be available

When you want to work with playlists, selecting one format for all of them doesn't work for all videos in it.
This is what I was referring to in issue #50

**Comment by MrS0m30n3** [comment]
Closing, since i dont believe anyone uses the **worst*** ones and under the [new gui](https://github.com/MrS0m30n3/youtube-dl-gui/tree/new_layout):
* default = best
* default + *extract audio from video file* (Formats tab) = bestaudio
* bestvideo is not available, but now the generic video formats are (mp4, webm, flv, etc..)
