### ISSUE TITLE
GUI Help

### ISSUE THREAD

**Issue by shogunreaper** [MrS0m30n3/youtube-dl-gui#147]
Can you add support for crunchyroll resolution in the gui? (i'm using the windows one from your site)

the only one that works for me is default (which seems to be 1080p and i want 720p), choosing anything else gets me "ERROR: requested format not available"

i can use -F to manually get the format code but i don't know how to add it in the GUI for multiple downloads at a time.

**Comment by MrS0m30n3** [comment]
Hi,

The old UI you are using is not maintained anymore, currently i'm working on the new UI.
The only solution under the old UI is to:

1. Set the video format to **default**
2. Run youtube-dl with the -F parameter
3. Go to Options>Commands tab and add this: `-f format_goes_here`

Unfortunately it is not possible to support all the video formats that youtube-dl provides.
If you have the time you can add the formats you are interested at to the new UI (see [new_layout branch](https://github.com/MrS0m30n3/youtube-dl-gui/tree/new_layout)) under the **formats.py** file, or just post them here so i can add them.

You can also check issues: https://github.com/MrS0m30n3/youtube-dl-gui/issues/116 https://github.com/MrS0m30n3/youtube-dl-gui/issues/111 https://github.com/MrS0m30n3/youtube-dl-gui/issues/110

### Note
Next time you will report an issue please fill in all the details asked and check the bug tracker else your issue is going to be marked as invalid

**Comment by shogunreaper** [comment]
so how do i add for commands for multiple videos at a time?

**Comment by MrS0m30n3** [comment]
You pass the same commands under Options>Commands that you would with **youtube-dl**.

**Comment by shogunreaper** [comment]
yeah but when i do it in a batch file i put the commands on each line for each separate link.

but i only get one box for all the commands in your program.

**Comment by MrS0m30n3** [comment]
>yeah but when i do it in a batch file i put the commands on each line for each separate link.

If that's you question then no you can't do that in **youtube-dlg**.
