### ISSUE TITLE
[Question] Interested in learning Python and windows executables

### ISSUE THREAD

**Issue by JunkyardCat** [MrS0m30n3/youtube-dl-gui#156]
Hi im interested in learning python and windows executable and want to understand how this work by reading your code. what do i need to run your python source code?

im getting error No module named wx when running the app but why is it i am able to run your executable without wxpython installed

**Comment by MrS0m30n3** [comment]
Requirements:
* Python 2.7+
* wxPython 2.9.1+
* twodict
* ffmpeg & ffprobe (to convert video files to audio-only files)

The reason you are able to run the executable with no errors is because the *wxPython* library is already packed to the executable to make it standalone. Also, i suggest you to check [py2exe](http://py2exe.org/) if you want to get your hands dirty with Python & Windows executables.

P.S.
Don't start with **youtube_dl_gui** since my code is a mess.

**Comment by JunkyardCat** [comment]
when do you plan to release the next update?

**Comment by MrS0m30n3** [comment]
See https://github.com/MrS0m30n3/youtube-dl-gui/issues/155
