### ISSUE TITLE
Need help; quality

### ISSUE THREAD

**Issue by Sonicpromo** [MrS0m30n3/youtube-dl-gui#190]
Hello
I can use a little help over here
1) I want to know if its possible to convert video with the settings I like after its downloaded (without 3rd party software but with the help of ffmpeg in example) i.e. 4k to 1080p with x-bitrate and framerate or 720p etc
2) I don't understand how to download 720p or 480p (not the best quality) with audio, limiting it in extra panel by command (-f "best[height=720]") wont work and the log will say that the format is not available even if it is because I can manually download it or select in browser

**Comment by nodiscc** [comment]
1. Yes. https://ffmpeg.org/documentation.html https://www.google.com/search?q=ffmpeg+re-encode https://stackexchange.com/search?q=ffmpeg http://www.commandlinefu.com/commands/matching/ffmpeg https://qwinff.github.io/
2. You can not limit the quality this way as far as I know. Please read https://github.com/rg3/youtube-dl/issues/168. You have to specify which formats you accept (numeric value like 38, 43...). See the [youtube-dl manual](https://github.com/rg3/youtube-dl/#format-selection) and direct your question there since this not related to youtube-dl-gui.

**Comment by Sonicpromo** [comment]
-f [height<480] is working for me but kinda strange it won't download better files instead some 640x360 while 720 and 800x480 are available

**Comment by nodiscc** [comment]
> Format selectors can also be grouped using parentheses, for example if you want to download the best mp4 and webm formats with a height lower than 480 you can use -f '(mp4,webm)[height<480]'.

This allows you to download formats *stricly* inferior to 480px height.

> If you want to only download some DASH formats (for example if you are not interested in getting videos with a resolution higher than 1080p), you can add -f bestvideo[height<=?1080]+bestaudio/best to your configuration file

You might need to try other operators like `[height<=?480]`
