### ISSUE TITLE
Archival Mode

### ISSUE THREAD

**Issue by ohhdemgirls** [MrS0m30n3/youtube-dl-gui#194]
Great, now can we please get an `Archival Mode` in this tool for people who actually care about doing this properly? I mean fantastic you can download a video but that's worthless without getting all related metadata, even more so if you plan to pass it to archive.org for long term storage.

youtube-dl already has all the necessary flags, please use them! `--add-metadata --write-description --write-annotations --write-info-json --all-subs --write-thumbnail`

**Comment by nodiscc** [comment]
@ohhdemgirls Since you already know which specific options you want to use I suggest you add them to `Options > Extra > Youtube-dl command-line options`.

Serious archival projects will want to use more complex setups involving command-line youtube-dl and a configuration file (eg `/.config/youtube-dl/config`  or `%APPDATA%/youtube-dl/config.txt`). You might also want to use the `--download-archive` option. The GUI cannot cater to all this without adding unneeded complexity. Some settings are already present (eg. `--all-subs`, `--add-metadata`, look through the options dialog) but if you want more flexibility, custom command line options are probably the way to go.

**Comment by ohhdemgirls** [comment]
@nodiscc I don't use this tool, just putting it out there and making sure other people are aware of this. I do all my archiving from the cli as suggested :+1:

**Comment by MrS0m30n3** [comment]
Also, note that `--write-description --write-annotations --write-info-json --write-thumbnail` were available in the previous versions but we removed them since nobody was using them.

So, as @nodiscc said the best way to achieve this behaviour is to add the appropriate commands under the *Extra* tab or use the CLI tool as you already do, closing.
