### ISSUE TITLE
Add cookies.txt

### ISSUE THREAD

**Issue by InfectedG** [MrS0m30n3/youtube-dl-gui#195]
### Feature request (request for a new functionality)

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

Add a tabs in option for put cookie.txt file : 

it would give : --cookies %parameter%.txt

Thank u

**Comment by nodiscc** [comment]
@InfectedG I don't think this is widely used (never had to use it in years), so adding it to the options dialog would needlessly clutter it. Since you seem to need it, know exactly why, and are familiar with youtube-dl command line options, I suggest you add it yourself to `Options > Extra > Youtube-dl command-line options`. Adding unneeded UI complexity for rare use cases is not desirable, using custom command-line flags is probably the way to go.

**Comment by InfectedG** [comment]
Oh nice, i didn't see it
