### ISSUE TITLE
Support use of git version of youtube-dl

### ISSUE THREAD

**Issue by yan12125** [MrS0m30n3/youtube-dl-gui#28]
youtube-dl usually releases rapidly. However, recently there's a long gap between releases. Is it possible to use the latest git version when 'update' is clicked? I've shortly examined how 'update' works. Seems we need at least a git library for python and a local installation of py2exe to achieve such a feature. With this feature, youtube-dl-gui can also use non-official forks (other than rg3's) as the backend. Any opinion?

**Comment by MrS0m30n3** [comment]
Hi @yan12125 

Yes it's possible to use the latest git version. There are two ways i can think of to make this work, you can either build youtube-dl binary on your own and change the update url on the updatemanager.py module (we could aslo add a new options tab so you can choose different update sources) to point to your own binary OR you can build the binary dynamically during the update process as you suggested, but you probably will need git and on Windows you also need py2exe. So i don't think building the binary on the update process is a good idea because the average user won't have git and py2exe installed. 

Also let me inform you that youtube-dl-gui can use non-official forks either by changing the update url as suggested or by changing the "youtubedl_path" options on the settings.json file to point to your own binary.

**Comment by yan12125** [comment]
Thanks for the information about the setting "youtubedl_path"! I'll try it.

Maybe another way is to establish a build server to eschew the need of py2exe on client-side.

**Comment by MrS0m30n3** [comment]
Notice that chaning the "youtubedl_path" wont change the update source. If you want to change the update source you need to edit https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/updatemanager.py#L48 this line. 

"Maybe another way is to establish a build server to eschew the need of py2exe on client-side."
That's what i meant when i told you that you can build your own binary. You basically build the binary, store it on a server and i could add a new options tab that will let you pick the update source but you will have to keep the binary updated else its pointless for most users.

This will also hold a security risk because a user may add a new "update server" which points to a malicious youtube-dl binary.

**Comment by yan12125** [comment]
In my opinion, users have responsibility if they choose to use an unofficial youtube-dl. Use of gpg verification can eliminate the possibility of hijacked binaries, but that's another long story to implement it in youtube-dl-gui...

After all, all posiible solutions is so costly against the rare event - no new youtube-dl releases in a long time span. The feature to use the git version of youtube-dl sounds exciting but may not be practical. Thanks for the discussion and sorry if annoying.

**Comment by nodiscc** [comment]
@yan12125 Wouldn't more frequent official youtube-dl releases solve this problem? Have you asked about it on their tracker.

**Comment by yan12125** [comment]
They usually do. By the way, such a feature is also useful for those who need an unofficial fork - not so many, though.

**Comment by MrS0m30n3** [comment]
@yan12125 Anyway i am closing this issue i don't think there are many users that will use this feauture. Also i think that the devs of youtube-dl release quite fast at least faster than i do :P
If you want you can either build your own binary and store it at the "youtubedl_path" or change the update url on the **updatemanager.py** as suggested.

Feel free to make more suggestions.
