### ISSUE TITLE
Unable to download the videos using DASH with audio

### ISSUE THREAD

**Issue by vishytk** [MrS0m30n3/youtube-dl-gui#327]
Using youtube-dlG version 0.4 on Fedora 28. I am trying to download some video in 1080p. I have selected "mp4 1080p DASH" but only the DASH video is downloaded with no audio. I do not see a way to select an option like "-f137+140" in youtube-dl command line.

I saw there is an old thread regarding the same issue but the issue was supposed to have been fixed. 

https://github.com/MrS0m30n3/youtube-dl-gui/issues/1

Here's what I have done. I have selected "**mp4 [1080p] (DASH Video)**" and the video link is https://www.youtube.com/watch?v=c3-4JvGSsaA from National Geographic.

Am I missing something or this is really an issue.

**Comment by Teiem** [comment]
I have the same problem - would be nice if someone could add an answer instead of just closing it

**Comment by monkeylove** [comment]
When I use the default setting, it downloads the video at 1080p with Opus audio.

I found one way to avoid Opus: configure the program to keep original files (in the formats tab of the options window). That way, you get the MP4 video that still has the AAC audio. The catch is that you need more disk space because the original files aren't deleted automatically.
