### ISSUE TITLE
Program freezes after opening the downoad folder

### ISSUE THREAD

**Issue by ThebestwaytodesignJoinGitHub** [MrS0m30n3/youtube-dl-gui#34]
Btw why does it open the folder?

**Comment by MrS0m30n3** [comment]
Hi,

I believe, that the destination folder opens because you have the 
"Open destination folder" option enabled under Options>Filesystem tab.

For me the program runs fine both on Windows and Linux.
Can you paste the content of your log file here?
Go to Options>Log tab and click the "View Log" button and paste the content here.

Also if you keep getting the same problem maybe you can update youtube-dl to the latest version.

**Comment by MrS0m30n3** [comment]
Anyway i am closing this. Feel free to re-open it if you want.
