### ISSUE TITLE
Is there a version for Mac/OS?

### ISSUE THREAD

**Issue by midas02** [MrS0m30n3/youtube-dl-gui#55]
Hello, sorry if this may be a stupid question, but I'm not very familiar with Mac. Somebody asked me if this software is also available for Mac, but all I can find is a deb-package, which is, I believe, meant for Linux. So could someone tell me if this programme has also been compiled for Mac or if there is an alternative version of it for Mac computers?

Many thanks!

**Comment by MrS0m30n3** [comment]
Hi @midas02 

Currently the easiest way to install youtube-dl-gui on Mac is [homebrew](http://brew.sh).
Youtube-dl-gui is not yet available on the official repo, in order to install it on your system you can run:

```
brew install https://raw.githubusercontent.com/pr0d1r2/homebrew-contrib/master/youtube-dl-gui.rb
```

**Note**
If wxPython is not installed on your system, you should check this [issue](https://github.com/pr0d1r2/homebrew-contrib/issues/1).

**Comment by midas02** [comment]
Ok thanks. I was hoping there would be a compiled GUI for Mac users. Apparently not then. Unfortunately running a command from the command line is beyond the means of most users. Maybe I'll ask a programming friend if he can't quickly fix up a GUI.

**Comment by MrS0m30n3** [comment]
Currently i don't have a Mac to try out the builds, that's the main reason there is no installer for Mac except from the homebrew way. Anyway, i'm closing this issue feel free to re-open it if you have more questions.
