### ISSUE TITLE
Debian 8 wxgtk2.8 not supported

### ISSUE THREAD

**Issue by rieftux** [MrS0m30n3/youtube-dl-gui#70]
Can't install it on Debain 8, because wxgtk2.8 is not released on Debian 8..

**Comment by nodiscc** [comment]
It looks like it is not present in Debian Jessie (probably because it had agrave bug? you have to investigate why). Howvere it is present in Sid and Wheezy https://packages.debian.org/search?keywords=python-wxgtk2.8. You might want to ask Debian maintainers about packaging it for Debian 8 Jessie. If I understand correctly it is a Debian bug, not youtube-dlg.

**Comment by MrS0m30n3** [comment]
I am closing this since it is a Debian bug.

**Comment by clessley** [comment]
Been watching this changelog: [http://www.ubuntuupdates.org/package/webupd8/xenial/main/base/youtube-dlg]

I was able to install on Ubuntu 16.04 LTS Xenial today!
